package com.example.battlecalculator

enum class PostureEnum {
    SCRN, DEF, RDEF, ADEF, ASL, FASL, TAC, REFT, MASL, ROAD, REC, MOV
}

enum class MovementModeEnum {
    COLUM, TACTICAL, DEPLOYED
}

enum class UnitTypeEnum {
    INFANTRY, MOTORIZED, TOWED_ARTILLERY, HELICOPTER, ARMOR, MECHANIZED, OTHER_ARTILLERY, RECON, HQ
}

enum class Alliances {
    NATO, PACT
}

enum class IntentExtraIDs {
    GAMESTATE, UNITSELECTIONTYPE
}

enum class UnitSelectionTypes {
    ATTACKER, DEFENDER, UNDEFINED
}

enum class FixedModifierEnum {
    NATO_DEFENDS_MULTI_COUNTRY, DEFENDER_RESTING, DEFENDER_ENGAGED, DEFENDER_HALF_ENGAGED, DEFENDER_DELAYED, DEFENDER_OUT_OF_COMMAND_SCREEN_REC, DEFENDER_OUT_OF_COMMAND, DEFENDER_FRONT_LINE_COMMAND, PACT_ATTACKING_REAR, PACT_DEFENDING_REAR, ATTACKER_HALF_ENGAGED, ATTACKER_OUT_OF_COMMAND, ATTACKER_OUT_OF_COMMAND_SCREEN_REC, ATTACKER_FRONT_LINE_COMMAND, ATTACKER_USES_REC, ATTACKER_USES_SAPPERS, DEFENDER_USES_SAPPERS
}

enum class CommandStateEnum {
    NORMAL, FRONT_LINE_COMMAND, OUT_OF_COMMAND
}

enum class EngagementStateEnum {
    NONE, HALF_ENGAGED, ENGAGED
}

enum class EwEffectEnum {
    ENEMY_AVIATION_HALVED, ENEMY_ARTILLERY_HALVED, ENEMY_COMMAND_DISRUPTED
}

enum class HourEnum {
    H00, H03, H06, H09, H12, H15, H18, H21
}

enum class DisengagemenResult {
    F1, S1, S0
}