package com.example.battlecalculator

enum class PostureEnum {
    SCRN, DEF, RDEF, ADEF, ASL, FASL, TAC, REFT, MASL, ROAD, REC, MOV
}

enum class MovementModeEnum {
    COLUM, TACTICAL, DEPLOYED
}

enum class UnitTypeEnum {
    INFANTRY, MOTORIZED, TOWED_ARTILLERY, HELICOPTER, ARMOR, MECHANIZED, OTHER_ARTILLERY, RECON, HQ
}

enum class Alliances {
    NATO, PACT
}

enum class IntentExtraIDs {
    GAMESTATE, UNITSELECTIONTYPE
}

enum class UnitSelectionTypes {
    ATTACKER, DEFENDER, UNDEFINED
}

enum class FixedModifierEnum {
    NATO_DEFENDS_MULTI_COUNTRY, DEFENDER_RESTING, DEFENDER_ENGAGED, DEFENDER_HALF_ENGAGED, DEFENDER_DELAYED, DEFENDER_OUT_OF_COMMAND_SCREEN_REC, DEFENDER_OUT_OF_COMMAND, DEFENDER_FRONT_LINE_COMMAND, PACT_ATTACKING_REAR, PACT_DEFENDING_REAR, ATTACKER_HALF_ENGAGED, ATTACKER_OUT_OF_COMMAND, ATTACKER_OUT_OF_COMMAND_SCREEN_REC, ATTACKER_FRONT_LINE_COMMAND
}